#!/bin/bash
# Licensed under the terms of the GNU GENERAL PUBLIC LICENSE v2, or any later version.

# Display cmus song informations

# Build array to hold song info
declare -a array
i=0
while read -r line; do
	string=($line)
	array[${i}]=${string[@]:1}
	((i++))
done < <(cmus-remote -Q)

# Assign array values to variables
status="${array[0]}"
file="${array[1]}"
time1="${array[2]}"
time2="${array[3]}"
song=${array[6]#* }

# Build string for song info
if [ "${array[4]%% *}" = "artist" ]; then
	artist="${array[4]#* }"
	playing="$artist - $song"
else # If no tag are set, display file name
	file=${file%.*}
	file=${file##*/}
	playing="$file"
fi

# Parse running time of song
t1=$(date -u -d @${time1} +"%M:%S")
t2=$(date -u -d @${time2} +"%M:%S")
duration="($t2/$t1)"

# Set icon depending of cmus status
case $status in
	"playing") icon="" ;;
	"paused") icon="" ;;
	"stopped"|*) icon="" playing="Music stopped" ;;
esac

# Commands on click event
case ${BLOCK_BUTTON} in
	# Left click, next song
	"1") cmus-remote -n ;;
	# Middle click, pause toggle
	"2") cmus-remote -u ;;
	# Right click, previous song
	"3") cmus-remote -r ;;
esac

# Return final string
echo "$icon $duration $playing"
