#!/bin/bash
# Licensed under the terms of the GNU GENERAL PUBLIC LICENSE v2, or any later version.

# Display cmus song
array="$(cmus-remote -Q)"
artist=$(echo "$array" | grep ' artist ' | cut -d ' ' -f3-)
song=$(echo "$array" | grep title | cut -d ' ' -f3-)
status=$(echo "$array" | grep status | cut -d ' ' -f2-)

time1=$(echo "$array" | grep duration | cut -d ' ' -f2)
time2=$(echo "$array" | grep position | cut -d ' ' -f2)

if [ "$time1" = "" ]; then
	playing=""
else
	t1=$(date -u -d @${time1} +"%M:%S")
	t2=$(date -u -d @${time2} +"%M:%S")
	playing="${playing//&}"
fi

# Parse running time of song
t1=$(date -u -d @${time1} +"%M:%S")
t2=$(date -u -d @${time2} +"%M:%S")
duration="($t2/$t1)"

# Set icon depending of cmus status
case $status in
	"playing") icon="" ;;
	"paused") icon="" ;;
	"stopped"|*) icon="" playing="Music stopped" ;;
esac

# Commands on click event
case ${BLOCK_BUTTON} in
	# Left click, next song
	"1") cmus-remote -n ;;
	# Middle click, pause toggle
	"2") cmus-remote -u ;;
	# Right click, previous song
	"3") cmus-remote -r ;;
esac

# Return final string
echo "$icon $duration $playing"
